### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by LercDsgn** [corpengine/corpengine#21]
### Why?
When you have a suggestion and want to discuss it with other people before opening an issue/pull request, you can just open a discussion. This increases collaboration and creates a place for more ideas to come in and be talked about. 

---
*See [this](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) article for how to enable discussions.*

**Comment by PyxleDev0** [comment]
sure thing
