### ISSUE TITLE
Development Version v1.3.dev1

### ISSUE THREAD

**Issue by LercDsgn** [corpengine/corpengine#35]
# Changes in v1.3.dev1
## Repo Changes
* "Enhancement Request" Issue Template
### Rearrangements
* Replaced following classes in main engine file with their own independent file (Resolves #29)
   - Colors
   - Version
   - Object
* Removed Flags class; moved its properties under Constants class.

**Comment by PyxleDev0** [comment]
the rearrangement is sitll not complete and there is some errors I have to deal with. We can't really call this a stable development version for now.

**Comment by LercDsgn** [comment]
> there is some errors I have to deal with

maybe open an issue or discussion
and if they're not issues about the current changes in this development version, we can just delay them to next versions?

> We can't really call this a stable development version

isn't a development version normally intented to be unstable already?

**Comment by LercDsgn** [comment]
uh, I see you already released?
